# Generated by Django 3.2.16 on 2022-12-15 18:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Максимум 32767', verbose_name='вес')),
            ],
            options={
                'verbose_name': 'курьерская служба',
                'verbose_name_plural': 'курьерские службы',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('text', ckeditor.fields.RichTextField(help_text='Подробно расскажите о впечатлениях от данной курьерской службы', verbose_name='описание')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='дата написания')),
                ('delivery', models.ForeignKey(help_text='Выберите курьерскую служба', on_delete=django.db.models.deletion.CASCADE, to='response.delivery', verbose_name='курьерская служба')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='previews/%Y/%m/%d', verbose_name='главное изображение товара')),
                ('response', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response', verbose_name='отзыв')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
