# Generated by Django 3.2.16 on 2022-12-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0009_alter_mainimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='another_link',
            field=models.CharField(blank=True, help_text='Добавьте сайты с отзывами об этой службе', max_length=200, null=True, verbose_name='другие отзывы'),
        ),
    ]
