# Generated by Django 3.2.16 on 2022-12-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0012_delivery_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='grade',
        ),
        migrations.AddField(
            model_name='response',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Отрицательный'), (2, 'Нейтральный'), (3, 'Положительный')], null=True, verbose_name='оценка'),
        ),
    ]
