# Generated by Django 3.2.16 on 2022-12-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0016_alter_mainimage_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='изображение к отзыву'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response', verbose_name='отзыв'),
        ),
    ]
