# Generated by Django 3.2.16 on 2022-12-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_alter_response_likes'),
        ('response', '0017_auto_20221220_1315'),
    ]

    operations = [
    ]
