# Generated by Django 3.2.16 on 2022-12-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0019_auto_20221222_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='weight',
        ),
    ]
