# Generated by Django 3.2.16 on 2022-12-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0013_auto_20221219_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(upload_to='previews/%Y/%m/%d', verbose_name='изображение к отзыву'),
        ),
        migrations.AlterField(
            model_name='response',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Отрицательная'), (2, 'Нейтральная'), (3, 'Положительная')], null=True, verbose_name='оценка'),
        ),
    ]
