# Generated by Django 3.2.16 on 2022-12-19 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0014_auto_20221219_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='изображение к отзыву'),
        ),
        migrations.AlterField(
            model_name='response',
            name='delivery',
            field=models.ForeignKey(help_text='Выберите курьерскую службу', on_delete=django.db.models.deletion.CASCADE, to='response.delivery', verbose_name='курьерская служба'),
        ),
    ]
